# Generated by Django 4.2.14 on 2024-11-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sql',
            name='content',
            field=models.TextField(default='nihao '),
            preserve_default=False,
        ),
    ]
